export const languageObject = {
  tr: {
    pinLeft: 'Sola Sabitle',
    pinRight: 'Sağa Sabitle',
    clearPin: 'Sabitlemeyi Kaldır',
    clearAllPins: 'Tüm Sabitleri Kaldır',
    prevPage: 'Önceki',
    nextPage: 'Sonraki',
    hideColumns: 'Sütunları Gizle',
    tableSettings: 'Tablo Ayarları',
    showAll: 'Tümünü Göster',
    hideAll: 'Tümünü Gizle',
    columnDrag: 'Sütun Sürükleme',
    columnPin: 'Sütun Sabitleme',
    recordCount: 'adet kayıt bulundu',
    filteredRecordCount: 'adet kayıt gösteriliyor',
    enabled: 'Aktif',
    disabled: 'Pasif',
    exportData: 'Dışa Aktar',
    fileFormat: 'Formatında',
    noData: 'Veri bulunamadı',
    filterNoData: 'Aradığınız kriterlere uygun sonuç bulunamadı',
    selectedItem: 'öğe seçildi',
    selectAll: 'Tümünü Seç',
    deselectAll: 'Tümünü Kaldır',
    applyFilter: 'Filtrele',
    saveSettings: 'Değişiklikleri Kaydet',
    loadMore: 'Devamını Yükle',
    emptyValues: 'Boş Değerler',
  },
  en: {
    pinLeft: 'Pin Left',
    pinRight: 'Pin Right',
    clearPin: 'Remove Pin',
    clearAllPins: 'Remove All Pins',
    prevPage: 'Previous',
    nextPage: 'Next',
    hideColumns: 'Hide Columns',
    tableSettings: 'Table Settings',
    showAll: 'Show All',
    hideAll: 'Hide All',
    columnDrag: 'Drag Columns',
    columnPin: 'Pin Columns',
    recordCount: 'items found',
    filteredRecordCount: 'items showed',
    enabled: 'Enabled',
    disabled: 'Disabled',
    exportData: 'Export Data',
    fileFormat: 'Format',
    noData: 'No data found',
    filterNoData: 'No data found for filtering',
    selectedItem: 'item selected',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    applyFilter: 'Filter',
    saveSettings: 'Save Settings',
    loadMore: 'Load More',
    emptyValues: 'Empty Values',
  },
};
